---
- name: add ROS repo key ~total runtime is 15-20 minutes~
  become: true
#  apt_key: "{{ ros_key }}"
  apt_key: id=421C365BD9FF1F717815A3895523BAEEB01FA116 keyserver=hkp://ha.pool.sks-keyservers.net:80

- name: add ROS repository
  become: true
  apt_repository:
    repo: 'deb http://packages.ros.org/ros/ubuntu xenial main'
#    repo: "{{ ros_repo }}"
    state: present
    update_cache: yes

- name: install ROS ~runtime is  10-15 minutes~
  become: true
  apt:
#    pkg: "{{ ros_pkg }}"
    pkg: ros-kinetic-desktop-full
    state: present
    update_cache: yes

- name: initialize rosdep
  shell: rosdep init

- name: update rosdep
  shell: rosdep update

- name: add ROS setup.bash file to ~/.bashrc
  shell: echo "source /opt/ros/kinetic/setup.bash" >> /home/cc/.bashrc
#===========================================
#- name: source the ROS setup.bash file
#  shell: source /opt/ros/kinetic/setup.bash
#===========================================
- name: install rosinstall
  apt:
    pkg: python-rosinstall
    state: present
    update_cache: yes

- name: install rosbash
  apt:
    pkg: rosbash
    state: present
    update_cache: yes
