#!/usr/bin/env bash

# wget https://raw.githubusercontent.com/cloudmesh/cloudmesh.ros/master/rosProjFinal/initiate

#create and prepare a three-node cluster
# cm cluster define -n rosA1 -c 3
# cm cluster allocate
# cm cluster cross_ssh

#capture info about cluster nodes
cm cluster nodes > node.list
cut -d' ' -f2 node.list > ~/ip.list
cut -d' ' -f1 node.list > ~/name.list

echo "README: IP Addresses and Names of Cluster Nodes:"
node01_ip=$(head -1 ~/ip.list)
echo "Node #1 IP Address: "$node01_ip
node01_nm=$(head -1 ~/name.list)
echo "Node #1 Name: "$node01_nm
# echo $node01_ip > mainNodeIP.list

node02_ip=$(sed -n '2p' ~/ip.list)
echo "Node #2 IP Address: "$node02_ip
node02_nm=$(sed -n '2p' ~/name.list)
echo "Node #2 Name: "$node02_nm

node03_ip=$(sed -n '3p' ~/ip.list)
echo "Node #3 IP Address: "$node03_ip
node03_nm=$(sed -n '3p' ~/name.list)
echo "Node #3 Name: "$node03_nm

rm ~/ip.list
rm ~/name.list

cm cluster inventory -o ~/inventoryInter.txt
echo "[master]" > ~/inventory.txt
echo $(sed -n '2p' ~/inventoryInter.txt) >> ~/inventory.txt
echo "[servants]" >> ~/inventory.txt
echo $(sed -n '3p' ~/inventoryInter.txt) >> ~/inventory.txt
echo $(sed -n '4p' ~/inventoryInter.txt) >> ~/inventory.txt

#add inventory.txt file to master node
rsync ~/inventory.txt cc@$node01_ip:/home/cc/ansibleScript/

rm ~/inventoryInter.txt
rm ~/inventory.txt

#connect to "master" node
# cm vm ssh -H $node01_nm
ssh -X cc@$node01_ip

# #add files necessary for upcoming steps to master node
# #use subversion to place the ansible files and the RoS robot files on the master node
# #use wget to place the rosSetup.yml file and inventory.txt file on the master node

# #ROS robot files
# svn export https://github.com/cloudmesh/cloudmesh.ros/trunk/rosProjFinal/mybot_ws /home/cc/mybot_ws

# #Ansible files
# mkdir ~/ansibleScript
# echo "README: Placing ansible files in "echo $(pwd)
# svn export https://github.com/cloudmesh/cloudmesh.ros/trunk/rosProjFinal/roles /home/cc/ansibleScript/roles
# cd ~/ansibleScript
# wget https://raw.githubusercontent.com/cloudmesh/cloudmesh.ros/master/rosProjFinal/rosSetup.yml

# wget https://raw.githubusercontent.com/cloudmesh/cloudmesh.ros/master/rosProjFinal/inventory.txt
