---
- hosts: all
  become: true
  roles:
    - identifySelf
    - treePkg
    - rosPkg
    - catkinPkg
- hosts: master
  become: true
    - rosEnvSetup



#======================================================
#  vars:
#    doc_root: /home/cc/ansibleInstall
#  tasks:
#    - name: create custom document root
#      file: path={{ doc_root }} state=directory owner=www-data group=www-data
#
#    - name: set up html file
#      copy: src=index.html dest={{ doc_root }}/index.html owner=www-data group=www-data
