#!/usr/bin/env bash
# 1) accept the veracity of the other nodes in the cluster; 
# 2) ansible seems to hang if this is not done first
# 3) run the ansible script
# 4) setup and start the robots

cut -d' ' -f1 ~/addMeToHostFiles.list > ~/inventoryInter.txt

node_ip01=$(sed -n '1p' ~/inventoryInter.txt)
echo $node_ip01
ssh -o StrictHostKeyChecking=no cc@$node_ip01 hostname

node_ip02=$(sed -n '2p' ~/inventoryInter.txt)
echo $node_ip02
ssh -o StrictHostKeyChecking=no cc@$node_ip02 hostname

node_ip03=$(sed -n '3p' ~/inventoryInter.txt)
echo $node_ip03
ssh -o StrictHostKeyChecking=no cc@$node_ip03 hostname

rm ~/inventoryInter.txt

# #add the ROS repo key to each machine
# #this started failing in the Ansible script at BOM May 2017
# ssh -o StrictHostKeyChecking=no cc@$node_ip01 sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
# ssh -o StrictHostKeyChecking=no cc@$node_ip02 sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
# ssh -o StrictHostKeyChecking=no cc@$node_ip03 sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116

#start the Ansible script
cd ~/ansibleScript
ansible-playbook -i inventory.txt rosSetup.yml

#prepare the mybot_ws workspace
cd /opt/ros/kinetic
source setup.bash
cd /home/cc/mybot_ws
catkin clean --yes
catkin build
source devel/setup.bash
echo "source /home/cc/mybot_ws/devel/setup.bash" >> /home/cc/.bashrc

ssh -o StrictHostKeyChecking=no cc@$node_ip03 hostname
# start talker.py on node #2
## start roscore
ssh cc@$node_ip02 wget -P /home/cc/ https://raw.githubusercontent.com/cloudmesh/cloudmesh.ros/master/code/talkListen
ssh -o StrictHostKeyChecking=no cc@$node_ip02 chmod +x /home/cc/talkListen

timeEnd=$SECONDS
totTime=$timeEnd-$timeBgn
echo "Run Time #1: $totTime sec" > /home/cc/timer.txt

ssh -o StrictHostKeyChecking=no cc@$node_ip02 ./talkListen
timeEnd=$SECONDS
totTime=$timeEnd-$timeBgn
echo "Total Run Time:  $totTime sec" >> /home/cc/timer.txt

# start the simulation and command the robots to move
source /home/cc/.bashrc
sleep 120 && rostopic pub /robot1/cmd_vel geometry_msgs/Twist '{linear: {x: 0.2, y: 0.0, z: 0.0}, angular: {x: 0.0, y: 0.0, z: 0.1}}'&
sleep 120 && rostopic pub /robot2/cmd_vel geometry_msgs/Twist '{linear: {x: 0.2, y: 0.0, z: 0.0}, angular: {x: 0.0, y: 0.0, z: 0.1}}'&
(
	sleep 30 && roslaunch mybot_gazebo mybot_world.launch
)

echo "beginAgain completed"