---
- name: add ROS repository
  become: true
  apt_repository:
    repo: 'deb http://packages.ros.org/ros/ubuntu xenial main'
    state: present
    update_cache: yes

- name: install ROS
  become: true
  apt:
    pkg: ros-kinetic-desktop-full
    state: present
    update_cache: yes

- name: initialize rosdep
  shell: rosdep init

- name: update rosdep
  shell: rosdep update

- name: add ROS setup.bash file to ~/.bashrc
  shell: echo "source /opt/ros/kinetic/setup.bash" >> /home/cc/.bashrc
- name: install rosinstall
  apt:
    pkg: python-rosinstall
    state: present
    update_cache: yes

- name: install rosbash
  apt:
    pkg: rosbash
    state: present
    update_cache: yes
